# See https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md
#
# This config will be combined with the central Guardian config in
# https://github.com/guardian/scala-steward-public-repos/blob/main/scala-steward.conf

updatePullRequests = "always"

pullRequests.frequency = "30 days"

pullRequests.grouping = [
  {
    name = "minor_and_patch",
    title = "chore(deps): Minor and patch updates",
    filter = [
      { version = "minor" },
      { version = "patch" }
    ]
  }
]
