package com.gu.devenv

import com.gu.devenv.modules.Modules
import com.gu.devenv.modules.Modules.ModuleConfig
import fansi.{Bold, Color}

import java.nio.file.Paths
import scala.util.{Failure, Success}

/** Natively compiled tool that wraps the Scala logic in a CLI program.
  */
object Main {
  enum Command {
    case Init, Generate, Check, Update, Version
    case Help
    case Unknown(name: String)
    case NoCommand
  }

  private val helpFlags = Set("help", "--help", "-h")

  /** Parses args into a Command, treating any help flag as a request for help regardless of
    * position.
    */
  def parseCommand(args: Seq[String]): Command =
    (args.headOption, args.lift(1)) match {
      case (Some(_), Some(flag)) if helpFlags.contains(flag) => Command.Help
      case (Some(cmd), _) if helpFlags.contains(cmd)         => Command.Help
      case (Some("init"), _)                                 => Command.Init
      case (Some("generate"), _)                             => Command.Generate
      case (Some("check"), _)                                => Command.Check
      case (Some("update"), _)                               => Command.Update
      case (Some("version" | "--version" | "-v"), _)         => Command.Version
      case (Some(unknown), _)                                => Command.Unknown(unknown)
      case (None, _)                                         => Command.NoCommand
    }

  def main(args: Array[String]): Unit = {
    val exitCode = parseCommand(args.toSeq) match {
      case Command.Init     => init()
      case Command.Generate => generate()
      case Command.Check    => check()
      case Command.Update   => update()
      case Command.Version =>
        printVersion()
        ExitCode.Success
      case Command.Help =>
        printPlainUsage()
        ExitCode.Success
      case Command.Unknown(name) =>
        System.err.println(Color.Red(s"Unknown command: $name"))
        printUsage()
        ExitCode.InvalidUsage
      case Command.NoCommand =>
        printUsage()
        ExitCode.InvalidUsage
    }
    if (exitCode != ExitCode.Success) {
      // for convenience in dev mode, only terminate with non-default exit codes
      sys.exit(exitCode.code)
    }
  }

  private val moduleConfig = ModuleConfig(mountKey = "devenv")

  /** Sets up a .devcontainer directory with nested subdirectories.
    *
    * Uses the project's devenv configuration file to generate:
    *   - .devcontainer/user/ (for user-specific devcontainer with merged preferences)
    *   - .devcontainer/shared/ (for project-specific devcontainer that can be checked in)
    *   - .devcontainer/.gitignore (to exclude user directory)
    *   - .devcontainer/devenv.yaml (project-specific configuration file)
    *
    * The devcontainer.json files can be generated by running the generate command after populating
    * the project's `devenv.yaml` settings file.
    */
  private def init(): ExitCode = {
    val devcontainerDir = Paths.get(".devcontainer")
    val tryResult = for {
      modules <- Modules.builtInModules(moduleConfig)
      result  <- Devenv.init(devcontainerDir, modules)
    } yield result
    tryResult match {
      case Success(result) =>
        println(Output.initResultMessage(result))
        ExitCode.Success
      case Failure(exception) =>
        System.err.println(s"Initialization failed: ${exception.getMessage}")
        exception.printStackTrace()
        ExitCode.Error
    }
  }

  /** Generates two devcontainer files for the current project, using the provided devenv
    * configuration.
    *
    * A user-specific file that includes properties merged from the users' own system-wide devenv
    * settings, and a generic user-agnostic devcontainer file that can be checked into the repo and
    * used for remote cloud devcontainers.
    */
  private def generate(): ExitCode = {
    val devcontainerDir = Paths.get(".devcontainer")
    val userConfigPath  = Paths.get(System.getProperty("user.home"), ".config", "devenv")
    val tryResult = for {
      modules <- Modules.builtInModules(moduleConfig)
      result  <- Devenv.generate(devcontainerDir, userConfigPath, modules)
    } yield result
    tryResult match {
      case Success(result) =>
        println(Output.generateResultMessage(result))
        if (result.successful) ExitCode.Success
        else ExitCode.Error
      case Failure(exception) =>
        System.err.println(s"Generation failed: ${exception.getMessage}")
        exception.printStackTrace()
        ExitCode.Error
    }
  }

  /** Checks whether the saved devcontainer.json files match what would be generated from the
    * current configuration.
    *
    * Validates that both user and shared devcontainer files are up-to-date with the current
    * devenv.yaml configuration. Useful for CI/CD to ensure configs are synchronized.
    */
  private def check(): ExitCode = {
    val devcontainerDir = Paths.get(".devcontainer")
    val userConfigPath  = Paths.get(System.getProperty("user.home"), ".config", "devenv")
    val tryResult = for {
      modules <- Modules.builtInModules(moduleConfig)
      result  <- Devenv.check(devcontainerDir, userConfigPath, modules)
    } yield result
    tryResult match {
      case Success(result) =>
        println(Output.checkResultMessage(result))
        if (result.successful) ExitCode.Success
        else ExitCode.Error
      case Failure(exception) =>
        System.err.println(s"Check failed: ${exception.getMessage}")
        exception.printStackTrace()
        ExitCode.Error
    }
  }

  private def update(): ExitCode = {
    val currentVersion = Version.release
    val architecture   = Version.architecture
    val branch         = Version.branch

    val result = Releases
      .fetchLatestRelease()
      .map { latestRelease =>
        Releases.checkForUpdate(
          currentVersion,
          architecture,
          branch,
          latestRelease
        )
      }
    println(
      Releases.formatUpdateCheckResult(result, currentVersion, architecture)
    )
    result match {
      case Success(updateResult) if updateResult.successful =>
        ExitCode.Success
      case _ =>
        ExitCode.Error
    }
  }

  /** Renders usage text with optional formatting applied to section titles and command names.
    *
    * @param title
    *   formats a section heading (e.g. bold)
    * @param cmd
    *   formats a command name (e.g. bold + cyan)
    */
  private def usageText(title: String => String, cmd: String => String): String = {
    val releaseLineStr = s"  release   ${Version.release}"
    val archLineStr    = Version.architecture.map(a => s"  arch      $a")
    val branchLineStr  = Version.branch.map(b => s"  branch    $b")
    val devModeNoteStr =
      if (Version.architecture.isEmpty && Version.branch.isEmpty)
        Some("  (running in development mode)")
      else
        None
    val versionInfoString =
      List(Some(releaseLineStr), archLineStr, branchLineStr, devModeNoteStr).flatten
        .mkString("\n")

    s"""${title("Usage:")} devenv <command> [--help]
       |
       |A CLI tool for managing devcontainer configurations for your projects.
       |Generates user-specific and shared devcontainer.json files from
       |devenv.yaml configuration files, separating team-wide project settings
       |from personal user preferences.
       |
       |Run 'devenv <command> --help' (or -h or help) for help on any command.
       |
       |${title("Commands:")}
       |
       |  ${cmd("init")}
       |    Initialises the .devcontainer directory structure for a project.
       |    Run this once from the root of a repository before using 'generate'.
       |    Reads:   nothing (uses built-in defaults)
       |    Writes:  .devcontainer/devenv.yaml        (project config template)
       |             .devcontainer/.gitignore         (excludes user/ directory)
       |             .devcontainer/README.md          (usage guidance)
       |             .devcontainer/shared/            (directory, populated by 'generate')
       |             .devcontainer/user/              (directory, populated by 'generate')
       |
       |  ${cmd("generate")}
       |    Generates devcontainer.json files from the current devenv configuration.
       |    Run this after editing devenv.yaml to apply your changes.
       |    Reads:   .devcontainer/devenv.yaml        (project config, required)
       |             ~/.config/devenv/devenv.yaml     (user config, optional)
       |    Writes:  .devcontainer/shared/devcontainer.json  (project-only, check in)
       |             .devcontainer/user/devcontainer.json    (merged with user prefs)
       |
       |  ${cmd("check")}
       |    Verifies that the saved devcontainer.json files match what 'generate'
       |    would produce from the current configuration. Exits non-zero if they
       |    differ. Use in CI to ensure configs are not stale.
       |    Reads:   .devcontainer/devenv.yaml
       |             ~/.config/devenv/devenv.yaml     (user config, optional)
       |             .devcontainer/shared/devcontainer.json
       |             .devcontainer/user/devcontainer.json
       |    Writes:  nothing
       |
       |  ${cmd("version")}
       |    Prints the current devenv release version, architecture, and branch.
       |    Aliases: --version, -v
       |
       |  ${cmd("update")}
       |    Checks GitHub releases for a newer version of devenv and prints
       |    download instructions if one is available.
       |
       |  ${cmd("help")}
       |    Prints this help text.
       |    Aliases: --help, -h
       |    Any command also accepts --help/-h as a second argument.
       |
       |${title("Configuration:")}
       |  Project config:  .devcontainer/devenv.yaml
       |    Project-specific settings (name, ports, IDE plugins, commands, modules).
       |    Checked into version control.
       |
       |  User config:     ~/.config/devenv/devenv.yaml
       |    Personal preferences (dotfiles, additional IDE plugins).
       |    Merged with project config for the user-specific devcontainer.
       |
       |${title("Typical workflow:")}
       |  1. devenv init       -- create initial config file
       |  2. edit .devcontainer/devenv.yaml
       |  3. devenv generate   -- produce devcontainer.json files
       |  4. devenv check      -- verify in CI that files are up to date
       |
       |${title("Version:")}
       |$versionInfoString
       |""".stripMargin
  }

  /** Coloured output for human use */
  private def printUsage(): Unit =
    println(usageText(s => Bold.On(s).toString, s => Bold.On(Color.Cyan(s)).toString))

  /** Plain text output for agent/tool use */
  private def printPlainUsage(): Unit =
    println(usageText(identity, identity))

  private def printVersion(): Unit = {
    // these properties are set at build time via environment variables
    // release defaults to "dev" for local development builds
    val releaseStr = Bold.On(Version.release).toString
    // architecture and branch have no fallbacks and will be empty when running locally
    val architectureStr = Version.architecture.fold("")(arch => s" ($arch)")
    val branchStr       = Version.branch.fold("")(branch => s" [$branch]")

    println(s"$releaseStr$architectureStr$branchStr")
  }

  /** Exit codes for the devenv CLI tool.
    *
    * Following Unix conventions:
    *   - 0 indicates success
    *   - 1 indicates a general error
    *   - 2 indicates invalid usage or command
    */
  private enum ExitCode(val code: Int) {
    case Success      extends ExitCode(0)
    case Error        extends ExitCode(1)
    case InvalidUsage extends ExitCode(2)
  }
}
