package com.gu.devenv

import com.gu.devenv.modules.Modules
import com.gu.devenv.modules.Modules.ModuleConfig
import fansi.{Bold, Color}

import java.nio.file.Paths
import scala.util.{Failure, Success}

/** Natively compiled tool that wraps the Scala logic in a CLI program.
  */
object Main {
  def main(args: Array[String]): Unit = {
    val exitCode = args.headOption match {
      case Some("init")     => init()
      case Some("generate") => generate()
      case Some("check")    => check()
      case Some("update")   => update()
      case Some("help" | "--help" | "-h") =>
        printUsage()
        ExitCode.Success
      case Some("version" | "--version" | "-v") =>
        printVersion()
        ExitCode.Success
      case Some(unknown) =>
        System.err.println(Color.Red(s"Unknown command: $unknown"))
        printUsage()
        ExitCode.InvalidUsage
      case None =>
        printUsage()
        ExitCode.InvalidUsage
    }
    if (exitCode != ExitCode.Success) {
      // for convenience in dev mode, only terminate with non-default exit codes
      sys.exit(exitCode.code)
    }
  }

  private val modules = Modules.builtInModules(
    ModuleConfig(mountKey = "devenv")
  )

  /** Sets up a .devcontainer directory with nested subdirectories.
    *
    * Uses the project's devenv configuration file to generate:
    *   - .devcontainer/user/ (for user-specific devcontainer with merged preferences)
    *   - .devcontainer/shared/ (for project-specific devcontainer that can be checked in)
    *   - .devcontainer/.gitignore (to exclude user directory)
    *   - .devcontainer/devenv.yaml (project-specific configuration file)
    *
    * The devcontainer.json files can be generated by running the generate command after populating
    * the project's `devenv.yaml` settings file.
    */
  def init(): ExitCode = {
    val devcontainerDir = Paths.get(".devcontainer")

    Devenv.init(devcontainerDir, modules) match {
      case Success(result) =>
        println(Output.initResultMessage(result))
        ExitCode.Success
      case Failure(exception) =>
        System.err.println(s"Initialization failed: ${exception.getMessage}")
        exception.printStackTrace()
        ExitCode.Error
    }
  }

  /** Generates two devcontainer files for the current project, using the provided devenv
    * configuration.
    *
    * A user-specific file that includes properties merged from the users' own system-wide devenv
    * settings, and a generic user-agnostic devcontainer file that can be checked into the repo and
    * used for remote cloud devcontainers.
    */
  def generate(): ExitCode = {
    val devcontainerDir = Paths.get(".devcontainer")
    val userConfigPath =
      Paths.get(System.getProperty("user.home"), ".config", "devenv")

    Devenv.generate(devcontainerDir, userConfigPath, modules) match {
      case Success(result) =>
        println(Output.generateResultMessage(result))
        if (result.successful) ExitCode.Success
        else ExitCode.Error
      case Failure(exception) =>
        System.err.println(s"Generation failed: ${exception.getMessage}")
        exception.printStackTrace()
        ExitCode.Error
    }
  }

  /** Checks whether the saved devcontainer.json files match what would be generated from the
    * current configuration.
    *
    * Validates that both user and shared devcontainer files are up-to-date with the current
    * devenv.yaml configuration. Useful for CI/CD to ensure configs are synchronized.
    */
  def check(): ExitCode = {
    val devcontainerDir = Paths.get(".devcontainer")
    val userConfigPath =
      Paths.get(System.getProperty("user.home"), ".config", "devenv")

    Devenv.check(devcontainerDir, userConfigPath, modules) match {
      case Success(result) =>
        println(Output.checkResultMessage(result))
        if (result.successful) ExitCode.Success
        else ExitCode.Error
      case Failure(exception) =>
        System.err.println(s"Check failed: ${exception.getMessage}")
        exception.printStackTrace()
        ExitCode.Error
    }
  }

  def update(): ExitCode = {
    val currentVersion = Version.release
    val architecture   = Version.architecture
    val branch         = Version.branch

    val result = Releases
      .fetchLatestRelease()
      .map { latestRelease =>
        Releases.checkForUpdate(
          currentVersion,
          architecture,
          branch,
          latestRelease
        )
      }
    println(
      Releases.formatUpdateCheckResult(result, currentVersion, architecture)
    )
    result match {
      case Success(updateResult) if updateResult.successful =>
        ExitCode.Success
      case _ =>
        ExitCode.Error
    }
  }

  private def printUsage(): Unit = {
    val header = s"${Bold.On("Usage:")} devenv <command>"
    // devenv commands
    val commandsTitle = Bold.On("Commands:")
    val initCmd       = Bold.On(Color.Cyan("init"))
    val generateCmd   = Bold.On(Color.Cyan("generate"))
    val checkCmd      = Bold.On(Color.Cyan("check"))
    val versionCmd    = Bold.On(Color.Cyan("version"))
    val updateCmd     = Bold.On(Color.Cyan("update"))
    val helpCmd       = Bold.On(Color.Cyan("help"))
    // version information
    val versionTitle   = Bold.On("Version:")
    val releaseLineStr = s"  release   ${Version.release}"
    val archLineStr    = Version.architecture.map(a => s"  arch      $a")
    val branchLineStr  = Version.branch.map(b => s"  branch    $b")
    val devModeNoteStr =
      if (Version.architecture.isEmpty && Version.branch.isEmpty) {
        Some("  (running in development mode)")
      } else {
        None
      }
    val versionInfoString =
      List(Some(releaseLineStr), archLineStr, branchLineStr, devModeNoteStr).flatten
        .mkString("\n")

    println(
      s"""$header
         |
         |Generates user-specific and shared devcontainer.json files from
         |devenv.yaml configuration files.
         |
         |$commandsTitle
         |  $initCmd      Initialize .devcontainer directory structure
         |  $generateCmd  Generate devcontainer.json files from devenv config
         |  $checkCmd     Ensure devcontainer.json files match current config
         |
         |  $versionCmd   Show devenv's version
         |  $updateCmd    Check for updates to devenv's CLI
         |
         |  $helpCmd      Show this help text
         |
         |$versionTitle
         |$versionInfoString
         |""".stripMargin
    )
  }

  private def printVersion(): Unit = {
    // these properties are set at build time via environment variables
    // release defaults to "dev" for local development builds
    val releaseStr = Bold.On(Version.release).toString
    // architecture and branch have no fallbacks and will be empty when running locally
    val architectureStr = Version.architecture.fold("")(arch => s" ($arch)")
    val branchStr       = Version.branch.fold("")(branch => s" [$branch]")

    println(s"$releaseStr$architectureStr$branchStr")
  }

  /** Exit codes for the devenv CLI tool.
    *
    * Following Unix conventions:
    *   - 0 indicates success
    *   - 1 indicates a general error
    *   - 2 indicates invalid usage or command
    */
  enum ExitCode(val code: Int) {
    case Success      extends ExitCode(0)
    case Error        extends ExitCode(1)
    case InvalidUsage extends ExitCode(2)
  }
}
